apiVersion: v1
kind: ServiceAccount
metadata:
  name: safeguard-csi-provider
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: safeguard-csi-provider
  name: safeguard-csi-provider
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: safeguard-csi-provider
  template:
    metadata:
      labels:
        app: safeguard-csi-provider
    spec:
      serviceAccountName: safeguard-csi-provider
      hostNetwork: true
      containers:
        - name: provider-safeguard-installer
          image: ghcr.io/oneidentity/safeguard-csi-provider:0.3.1
          imagePullPolicy: IfNotPresent
          args:
            - --endpoint=unix:///provider/safeguard.sock
            - --healthz-port=8989
            - --healthz-path=/healthz
            - --healthz-timeout=5s
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8989
            failureThreshold: 3
            initialDelaySeconds: 5
            timeoutSeconds: 10
            periodSeconds: 30
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
            limits:
              cpu: 50m
              memory: 100Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsUser: 0
            capabilities:
              drop:
              - ALL
          volumeMounts:
            - mountPath: "/provider"
              name: providervol
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: type
                operator: NotIn
                values:
                - virtual-kubelet
      volumes:
        - name: providervol
          hostPath:
            path: "/etc/kubernetes/secrets-store-csi-providers"
      nodeSelector:
        kubernetes.io/os: linux
