apiVersion: v1
data:
  clientid: ZWU4YzYzZDktNzE3NC00MWE1LWIzMDktZGVhMzZjNjMxMWI5
  clientsecret: xyz
kind: Secret
metadata:
  labels:
    secrets-store.csi.k8s.io/used: "true"
  name: secrets-store-creds
type: Opaque