apiVersion: v2
name: safeguard-csi-provider
version: 0.3.1
appVersion: 0.3.1
kubeVersion: ">=1.16.0-0"
description: A Helm chart to install the Secrets Store CSI Driver inside a Kubernetes cluster.
sources:
  - https://github.com/OneIdentity/safeguard-csi-provider
home: https://github.com/OneIdentity/safeguard-csi-provider
maintainers:
  - name: Dane Barentine
    email: dane.barentine@oneidentity.com
  - name: Andy Holloway
    email: andy.holloway@oneidentity.com