# One or more secrets to be used when pulling images
imagePullSecrets: []
# - name: myRegistryKeySecretName

# logging format json
# Default is text.
logFormatJSON: false

# log level. Uses V logs (klog)
logVerbosity: 0

linux:
  image:
    repository: starlingdev.azurecr.io/oneidentity/secrets-store/provider-safeguard
    tag: v0.2.0
    pullPolicy: IfNotPresent
  nodeSelector: {}
  tolerations: []
  enabled: true
  resources:
    requests:
      cpu: 50m
      memory: 100Mi
    limits:
      cpu: 50m
      memory: 100Mi
  podLabels: {}
  podAnnotations: {}
  priorityClassName: ""
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  privileged: false
  healthzPort: 8989
  healthzPath: "/healthz"
  healthzTimeout: "5s"
  volumes: []
  volumeMounts: []
  kubeletRootDir: /var/lib/kubelet
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: type
            operator: NotIn
            values:
            - virtual-kubelet

windows:
  image:
    repository: starlingdev.azurecr.io/oneidentity/secrets-store/provider-safeguard
    tag: v0.2.0
    pullPolicy: IfNotPresent
  nodeSelector: {}
  tolerations:
  - key: "node.kubernetes.io/os"
    operator: "Equal"
    value: "windows"
    effect: "NoSchedule"
  enabled: false
  resources:
    requests:
      cpu: 100m
      memory: 200Mi
    limits:
      cpu: 100m
      memory: 200Mi
  podLabels: {}
  podAnnotations: {}
  priorityClassName: ""
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  healthzPort: 8989
  healthzPath: "/healthz"
  healthzTimeout: "5s"
  volumes: []
  volumeMounts: []
  kubeletRootDir: C:\var\lib\kubelet
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: type
            operator: NotIn
            values:
            - virtual-kubelet

## Install default service account
rbac:
  install: true
  pspEnabled: false
